#!/bin/bash

if (( $# != 1 )); then
    echo "./menu_exit_openbox reboot  or  ./menu_exit_openbox poweroff  !!!"
    exit 0
fi

if [[ $1 == 'reboot' ]]; then
    zenity --question --no-wrap --title "Перезагрузить ПК" --text "Вы действительно хотите перезагрузить Компьютер?" && reboot
elif [[ $1 == 'poweroff' ]]; then
    zenity --question --no-wrap --title "Выключить ПК" --text "Вы действительно хотите выключить Компьютер?" && poweroff
else
    echo "./menu_exit_openbox reboot  or  ./menu_exit_openbox poweroff  !!!"
fi

